from __future__ import annotations
import ast, hashlib, json, pprint
from pathlib import Path
from typing import Any
import jsonschema
from .common import SCHEMA_NAME, GENERATED_NAME, load_json, write_json, safe_artifact_path, sha256_file
from .pdf_ops import pdf_structural_hash


def resolve_root(config_path: Path):
    state = load_json(config_path)
    root = (config_path.parent / state['artifact_root']).resolve()
    schema = load_json(root / SCHEMA_NAME)
    jsonschema.validate(state, schema)
    return root, state, schema


def export_generated_python(root: Path, state: dict) -> Path:
    out = root / GENERATED_NAME
    body = pprint.pformat(state, width=110, sort_dicts=False)
    out.write_text('# AUTO-GENERATED by pdf_system_engine.py\n# Python mirror of validated pdf_system_config.json.\n\nSYSTEM_STATE = ' + body + '\n', encoding='utf-8')
    return out


def import_generated_python(root: Path) -> dict:
    path = root / GENERATED_NAME
    tree = ast.parse(path.read_text(encoding='utf-8'), filename=str(path))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == 'SYSTEM_STATE' for t in node.targets):
            state = ast.literal_eval(node.value)
            if not isinstance(state, dict): raise RuntimeError('BLOCK: SYSTEM_STATE must be a dict')
            jsonschema.validate(state, load_json(root / SCHEMA_NAME))
            return state
    raise RuntimeError('BLOCK: generated_rules.py has no literal SYSTEM_STATE')


def primary_state(root: Path, state: dict) -> dict[str, str]:
    out = {}
    for rel in state['convergence']['primary_state_files']:
        p = safe_artifact_path(root, rel)
        if not p.exists(): out[rel] = 'MISSING'
        elif p.suffix.lower() == '.pdf': out[rel] = pdf_structural_hash(p)
        elif p.suffix.lower() == '.json': out[rel] = hashlib.sha256(json.dumps(load_json(p), sort_keys=True, separators=(',', ':')).encode()).hexdigest()
        else: out[rel] = sha256_file(p)
    return out
